---
name: "CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer
      - uses: actions/checkout@v4
      - name: Run Tests
        run: swift test -v
